id: PF248F75B
initial_creation_type: ocr
source_metadata:
  volumes:
    2e8a964d22674c4b9944edc11b73f331:
      base_file: v049.txt
      image_group_id: I1PD95894
      title: འཕགས་པ་ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པ་སྟོང་ཕྲག་ཉི་ཤུ་ལྔ་པའི་མན་ངག་གི་བསྟན་བཅོས་མངོན་པར་རྟོགས་པའི་རྒྱན་གྱི་ཚིག་ལེའུར་བྱས་པའི་རྣམ་པར་འགྲེལ་པ།
      total_pages: 1182
      volume_number: 49
